# Generated by Django 5.1.1 on 2024-09-21 19:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "noAdmin",
                    models.PositiveBigIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("namaAdmin", models.CharField(max_length=255)),
                ("emailAdmin", models.CharField(max_length=255, unique=True)),
                ("nomorHpAdmin", models.CharField(max_length=13, unique=True)),
                ("alamatAdmin", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "role",
                    models.IntegerField(
                        choices=[(1, "Customer"), (2, "Device"), (3, "Admin")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "noCust",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("namaCust", models.CharField(max_length=255)),
                ("emailCust", models.CharField(max_length=255, unique=True)),
                ("nomorHpCust", models.CharField(max_length=13, unique=True)),
                ("pesanCust", models.CharField(max_length=255)),
                ("alamatCust", models.CharField(max_length=255)),
                ("tanggalSewa", models.DateField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playbox2.admins",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "noDevice",
                    models.PositiveBigIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(9999),
                        ],
                    ),
                ),
                ("namaDevice", models.CharField(max_length=255)),
                ("fasilitas", models.CharField(max_length=255)),
                ("bonus", models.CharField(max_length=255)),
                ("tanggalMasuk", models.DateField()),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playbox2.admins",
                    ),
                ),
            ],
        ),
    ]
